// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD25NQ-4IruSRU4q9WUfvV4ICncSqe-fRw',
    appId: '1:454157987904:web:72331784893e4945da6fa5',
    messagingSenderId: '454157987904',
    projectId: 'kiemtra-firebase-27-12',
    authDomain: 'kiemtra-firebase-27-12.firebaseapp.com',
    storageBucket: 'kiemtra-firebase-27-12.firebasestorage.app',
    measurementId: 'G-LTBF3WQ59K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97drUcyLRtgeJ8vrEq1ddVidPzStsGE0',
    appId: '1:454157987904:android:6657913effc63d4bda6fa5',
    messagingSenderId: '454157987904',
    projectId: 'kiemtra-firebase-27-12',
    storageBucket: 'kiemtra-firebase-27-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1kqIDIzXScVXv8VIwX73_4vPsX3iJdk',
    appId: '1:454157987904:ios:060bf44237f14e60da6fa5',
    messagingSenderId: '454157987904',
    projectId: 'kiemtra-firebase-27-12',
    storageBucket: 'kiemtra-firebase-27-12.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2251172255',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1kqIDIzXScVXv8VIwX73_4vPsX3iJdk',
    appId: '1:454157987904:ios:060bf44237f14e60da6fa5',
    messagingSenderId: '454157987904',
    projectId: 'kiemtra-firebase-27-12',
    storageBucket: 'kiemtra-firebase-27-12.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2251172255',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD25NQ-4IruSRU4q9WUfvV4ICncSqe-fRw',
    appId: '1:454157987904:web:1db52c40c5ea0d5dda6fa5',
    messagingSenderId: '454157987904',
    projectId: 'kiemtra-firebase-27-12',
    authDomain: 'kiemtra-firebase-27-12.firebaseapp.com',
    storageBucket: 'kiemtra-firebase-27-12.firebasestorage.app',
    measurementId: 'G-6M22TBT7C9',
  );
}
